# Generated by Django 6.0.2 on 2026-02-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='battle',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='battle',
            name='date',
            field=models.DateField(verbose_name='Battle Date'),
        ),
    ]
