# Generated by Django 6.0.2 on 2026-02-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_alter_battle_options_alter_battle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
